# Join Sets in Python

set1={"A","B","C"}
set2={1,2,3}
set3={"John","Elena"}
set4={"Apple","Bananas","Cherry"}
mySet=set1.union(set2)
print(mySet)
mySet=set1|set2
print(mySet)
mySet=set1.union(set2,set3,set4)
print(mySet)
mySet=set1|set2|set3|set4
print(mySet)
x={"A","B","C"}
y=(1,2,3)
z=x.union(y)
print(z)
set1.update(set2)
print(set1)
set1={"Apple","Banana","Cherry"}
set2={"Google","Microsoft","Apple"}
set3=set1.intersection(set2)
print(set3)
set3=set1&set2
print(set3)
set1.intersection_update(set2)
print(set1)
set1={"Apple",1,"Banana",0,"Cherry"}
set2={False,"Google",1,"Apple",2,True}
set3=set1.intersection(set2)
print(set3)
set1={"Apple","Banana","Cherry"}
set2={"Google","Microsoft","Apple"}
set3=set1.difference(set2)
print(set3)
set3=set1-set2
print(set3)
set1.difference_update(set2)
print(set1)
set1={"Apple","Banana","Cherry"}
set2={"Google","Microsoft","Apple"}
set3=set1.symmetric_difference(set2)
print(set3)
set3=set1^set2
print(set3)
set1.symmetric_difference_update(set2)
print(set1)