# NumPy Creating Arrays in Python

import numpy as np
print(f"\nCreating an Array using NumPy\n")
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
arr=np.array((1,2,3,4,5))
print(arr)
print(f"\n0-D Arrays\n")
arr=np.array(42)
print(arr)
print(f"\n1-D Arrays\n")
arr=np.array([1,2,3,4,5])
print(arr)
print(f"\n2-D Arrays\n")
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(f"\n3-D Arrays\n")
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)
print(f"\nCheck Number of Dimensions\n")
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(f"\nHigher Dimensional Arrays\n")
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("Number of Dimensions:",arr.ndim)